version: '3.8'

services:
  proxy-api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
    depends_on:
      - mysql
    env_file:
      - .env
    ports:
      - "8888:8888"
      - "8090:8090"
    networks:
      - futures-pro
#  redis:
#    image: redis:7.0.5-alpine
#    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
#    ports:
#      - 6379:6379
  mysql:
    image: mysql:8
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - futures-pro
volumes:
  db_data:
networks:
  futures-pro:
    external: true
